parameters:
  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: RelativePathToTerraformFiles
    type: string
    default: ''
    displayName: 'Target Path to Terraform files (.tf,.tfvars) that require publishing as artifact'

  - name: AdditionalFilesToPackage
    type: object
    default: [ ]
    displayName: 'List of additional files to include in the terraform artifact (SourceDirectory, FilesPattern, TargetSubdirectoryName)'

  - name: TerraformBuildInjectionSteps
    type: stepList
    default: [ ]
    displayName: 'Steps to be carried out before the terraform is init, validated, and packaged'

  - name: EnvironmentConfigs
    type: object
    # NO default - Consumer must provide this
    displayName: 'List of environment configurations (see docs/definition_docs/terraform_pipeline/environment_config.md)'

  - name: IsDestroy
    type: boolean
    default: false
    displayName: 'Indicates if the terraform destroy command should be executed'

stages:
  - template: /stages/terraform_build.yml
    parameters:
      RelativePathToTerraformFiles: ${{ parameters.RelativePathToTerraformFiles }}
      AdditionalFilesToPackage: ${{ parameters.AdditionalFilesToPackage }}
      TerraformVersion: ${{ parameters.TerraformVersion }}
      TerraformBuildInjectionSteps: ${{ parameters.TerraformBuildInjectionSteps }}

  - ${{ each environmentConfig in parameters.EnvironmentConfigs }}:
      - template: /stages/terraform_deploy.yml
        parameters:
          ${{ if or(not(environmentConfig.Name), eq(environmentConfig.Name, '')) }}:
            "an environment name is not properly defined and is a required field.": "Error"
          TerraformVersion: ${{ parameters.TerraformVersion }}
          IsDestroy: ${{ parameters.IsDestroy }}
          EnvironmentConfig: ${{ environmentConfig }}
