parameters:
  # generic parameters
  - name: TerraformDeployMode
    type: string
    default: Plan
    values:
      - Apply
      - Plan
      - Destroy
    displayName: 'The terraform deploy mode: plan, apply, or destroy'

  - name: CheckoutAlias
    type: string
    default: AzDOPipelineTemplates
    values:
      - AzDOPipelineTemplates
      - self
    displayName: 'The checkout alias for the template repository (testing purposes)'

  - name: Condition
    type: string
    default: succeeded()
    displayName: 'The condition that will control whether this job runs or not'

  - name: DependsOn
    type: object
    default: [ ]
    displayName: 'List of jobs this job depends on'

  - name: Pool
    type: string
    default: ''
    displayName: 'The pool that this job will run on'

  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: EnvironmentName
    type: string
    # NO default - Consumer must provide this
    displayName: 'The environment name that the infrastructure is for'

  - name: TerraformDeploymentConfig
    type: object
    # NO default - Consumer must provide this
    displayName: 'Terraform deployment configuration object (see docs/definition_docs/terraform_pipeline/terraform_deployment_config.md)'

jobs:
  - template: /schemas/terraform_deployment_config.yml
    parameters:
      TerraformDeploymentConfig: ${{ parameters.TerraformDeploymentConfig }}
      EnvironmentName: ${{ parameters.EnvironmentName }}

  - deployment: TerraformDeploy${{ parameters.TerraformDeployMode }}_${{ parameters.TerraformArtifactName }}
    displayName: "${{ parameters.TerraformDeployMode }} '${{ parameters.TerraformArtifactName }}' Terraform Artifact"

    condition: ${{ parameters.Condition }}
    dependsOn: ${{ parameters.DependsOn }}
    ${{ if parameters.Pool }}:
      pool: ${{ parameters.Pool }}
    workspace:
      clean: all

    environment: ${{ parameters.TerraformDeploymentConfig.AzDOEnvironmentName }}

    variables:

      # Terraform Plan Variables
      - ${{ if eq(parameters.TerraformDeployMode, 'Plan') }}:
          - name: TerraformPlanFilePath
            value: $(TerraformWorkingDirectory)/tfplan
          - name: TerraformPlannedChangesFilePath
            value: $(TerraformWorkingDirectory)/terraform-planned-changes.json

      # Terraform Apply Variables
      - ${{ if eq(parameters.TerraformDeployMode, 'Apply') }}:
          - name: TerraformOutputVariablesCommandOption
            value: ${{ join(',', parameters.TerraformDeploymentConfig.OutputVariables) }}
          - name: TerraformOutputVariablesFilePath
            value: $(TerraformWorkingDirectory)/terraform-output-variables.json

      # Shared Variables
      - template: /utils/concat_wrap_list.yml
        parameters:
          Items: ${{ parameters.TerraformDeploymentConfig.VariableFiles }}
          Prefix: ' -var-file="$(TerraformWorkingDirectory)/'
          Suffix: '"'
          OutputVariableName: VariableFilesCommandOption

      - template: /utils/concat_wrap_list.yml
        parameters:
          Items:
            - ${{ each backendConfig in parameters.TerraformDeploymentConfig.BackendConfig }}:
                - "${{ backendConfig.Key }}=${{ backendConfig.Value }}"
          Prefix: ' -backend-config="'
          Suffix: '"'
          OutputVariableName: BackendConfigCommandOption

      - name: TerraformWorkingDirectory
        value: $(Pipeline.Workspace)/${{ parameters.TerraformArtifactName }}
      - name: CheckoutPath
        value: devops-azdo-yaml-pipeline-templates
      - name: ScriptDirectory
        value: $(Pipeline.Workspace)/$(CheckoutPath)/scripts

      - ${{ if parameters.TerraformDeploymentConfig.JobsVariableMappings }}: # Only run validation if the optional parameter is present
          - ${{ each mapping in parameters.TerraformDeploymentConfig.JobsVariableMappings }}:
              - ${{ if mapping.template }}:
                  - template: ${{ mapping.template }}@self
              - ${{ if or(mapping.name, mapping.group) }}:
                  - ${{ mapping }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: ${{ parameters.CheckoutAlias }}
              persistCredentials: true
              path: $(CheckoutPath)

            - download: none

            - template: /tasks/download_pipeline_artifact.yml
              parameters:
                ArtifactName: ${{ parameters.TerraformArtifactName }}
                TargetPath: $(TerraformWorkingDirectory)

            - template: /tasks/terraform_installer.yml
              parameters:
                TerraformVersion: ${{ parameters.TerraformVersion }}

            - ${{ if parameters.TerraformDeploymentConfig.ConfigSources }}:
                - template: /utils/config_sources_task_list.yml
                  parameters:
                    ConfigSources: ${{ parameters.TerraformDeploymentConfig.ConfigSources }}

            - ${{ if and(parameters.TerraformDeploymentConfig.KeyVaultConfig.ServiceConnection, parameters.TerraformDeploymentConfig.KeyVaultConfig.Name, parameters.TerraformDeploymentConfig.KeyVaultConfig.SecretsFilter) }}:
                - template: /tasks/azure_key_vault.yml
                  parameters:
                    KeyVaultServiceConnection: ${{ parameters.TerraformDeploymentConfig.KeyVaultConfig.ServiceConnection }}
                    KeyVaultName: ${{ parameters.TerraformDeploymentConfig.KeyVaultConfig.Name }}
                    SecretsFilter: ${{ parameters.TerraformDeploymentConfig.KeyVaultConfig.SecretsFilter }}

            - template: /tasks/terraform.yml
              parameters:
                Command: init
                CommandOptions: $(BackendConfigCommandOption) ${{ iif(parameters.TerraformDeploymentConfig.AzureServiceConnection, '-backend-config="use_azuread_auth=true"', '') }}
                WorkingDirectory: $(TerraformWorkingDirectory)
                TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                  ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}

            - ${{ if eq(parameters.TerraformDeployMode, 'Plan') }}:
                - template: /tasks/terraform.yml
                  parameters:
                    Command: plan
                    CommandOptions: -out=$(TerraformPlanFilePath) $(VariableFilesCommandOption) -input=false
                    WorkingDirectory: $(TerraformWorkingDirectory)
                    TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                    ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                      ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}

                - ${{ if parameters.TerraformDeploymentConfig.VerificationMode }}:
                    - template: /tasks/terraform.yml
                      parameters:
                        Command: custom
                        CustomCommand: show
                        CommandOptions: -json $(TerraformPlanFilePath)
                        SaveCommandConsoleOutputToFile: true
                        CommandConsoleOutputFileName: $(TerraformPlannedChangesFilePath)
                        WorkingDirectory: $(TerraformWorkingDirectory)
                        TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                        ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                          ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}

                    - template: /tasks/powershell.yml
                      parameters:
                        TaskName: TerraformChangesCheck
                        TargetType: filePath
                        ScriptFilePath: $(ScriptDirectory)/terraform/terraform_changes_check.ps1
                        ScriptFileArguments: >
                          -VerificationMode ${{ parameters.TerraformDeploymentConfig.VerificationMode }}
                          -TerraformPlannedChangesFilePath $(TerraformPlannedChangesFilePath)
                        FailOnStandardError: true
                        UsePowerShellCoreOnWindows: true

            - ${{ if eq(parameters.TerraformDeployMode, 'Apply') }}:
                - template: /tasks/terraform.yml
                  parameters:
                    Command: apply
                    CommandOptions: $(VariableFilesCommandOption) -input=false -auto-approve
                    WorkingDirectory: $(TerraformWorkingDirectory)
                    TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                    ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                      ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}
            
            - ${{ if eq(parameters.TerraformDeployMode, 'Destroy') }}:
                - template: /tasks/terraform.yml
                  parameters:
                    Command: destroy
                    CommandOptions: $(VariableFilesCommandOption) -input=false -auto-approve
                    WorkingDirectory: $(TerraformWorkingDirectory)
                    TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                    ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                      ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}

                - ${{ if parameters.TerraformDeploymentConfig.OutputVariables }}:
                    - template: /tasks/terraform.yml
                      parameters:
                        Command: output
                        CommandOptions: -json
                        SaveCommandConsoleOutputToFile: true
                        CommandConsoleOutputFileName: $(TerraformOutputVariablesFilePath)
                        WorkingDirectory: $(TerraformWorkingDirectory)
                        TaskEnvironmentVariables: ${{ parameters.TerraformDeploymentConfig.EnvironmentVariableMappings }}
                        ${{ if parameters.TerraformDeploymentConfig.AzureServiceConnection }}:
                          ServiceConnection: ${{ parameters.TerraformDeploymentConfig.AzureServiceConnection }}

                    - template: /tasks/powershell.yml
                      parameters:
                        TaskName: TerraformExportOutputsVariables
                        TargetType: filePath
                        ScriptFilePath: $(ScriptDirectory)/terraform/terraform_export_outputs.ps1
                        ScriptFileArguments: >
                          -OutputVariablesToExport $(TerraformOutputVariablesCommandOption)
                          -OutputFileName $(TerraformOutputVariablesFilePath)
                        FailOnStandardError: true
                        UsePowerShellCoreOnWindows: true
