parameters:
  - name: Condition
    type: string
    default: succeeded()
    displayName: 'The condition that will control whether this job runs or not'

  - name: DependsOn
    type: object
    default: [ ]
    displayName: 'List of jobs this job depends on'

  - name: Pool
    type: string
    default: ''
    displayName: 'The pool that this job will run on'

  - name: CheckoutAlias
    type: string
    default: AzDOPipelineTemplates
    values:
      - AzDOPipelineTemplates
      - self
    displayName: 'The checkout alias for the template repository (testing purposes)'

  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: EnvironmentName
    type: string
    # NO default - Consumer must provide this
    displayName: 'The environment name that the infrastructure is for'

  - name: TerraformDeploymentConfig
    type: object
    # NO default - Consumer must provide this
    displayName: 'Terraform deployment configuration object (see docs/definition_docs/terraform_pipeline/terraform_deployment_config.md)'
  
  - name: IsDestroy
    type: boolean
    default: false
    displayName: 'Indicates if the terraform destroy command should be executed'

jobs:
  - ${{ if in(parameters.TerraformDeploymentConfig.RunMode, 'PlanVerifyApply', 'PlanOnly') }}:
      - template: /jobs/terraform_deploy.yml
        parameters:
          CheckoutAlias: ${{ parameters.CheckoutAlias }}
          # generic parameters
          TerraformDeployMode: Plan
          Condition: ${{ parameters.Condition }}
          DependsOn: ${{ parameters.DependsOn }}
          Pool: ${{ parameters.Pool }}
          TerraformArtifactName: ${{ parameters.TerraformArtifactName }}
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformDeploymentConfig: ${{ parameters.TerraformDeploymentConfig }}
          EnvironmentName: ${{ parameters.EnvironmentName }}

  - ${{ if eq(parameters.TerraformDeploymentConfig.RunMode, 'PlanVerifyApply') }}:
      - template: /jobs/manual_verification.yml
        parameters:
          JobName: ManualVerification_${{ parameters.TerraformArtifactName }}
          Condition: and(succeeded(), eq(dependencies.TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.outputs['TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.TerraformChangesCheck.ChangesNeedManualVerification'], 'true'))
          DependsOn: TerraformDeployPlan_${{ parameters.TerraformArtifactName }}
          Instructions: 'Please validate the terraform plan is acceptable to apply'


  - ${{ if and(in(parameters.TerraformDeploymentConfig.RunMode, 'PlanVerifyApply', 'ApplyOnly'), eq(parameters.IsDestroy, false)) }}:
      - template: /jobs/terraform_deploy.yml
        parameters:
          CheckoutAlias: ${{ parameters.CheckoutAlias }}
          # generic Parameters
          TerraformDeployMode: Apply
          ${{ if eq(parameters.TerraformDeploymentConfig.RunMode, 'ApplyOnly') }}:
            DependsOn: ${{ parameters.DependsOn }}
            Condition: ${{ parameters.Condition }}
          ${{ if eq(parameters.TerraformDeploymentConfig.RunMode, 'PlanVerifyApply') }}:
            Condition: >
              or(
                succeeded('ManualVerification_${{ parameters.TerraformArtifactName }}'),
                and(
                  succeeded('TerraformDeployPlan_${{ parameters.TerraformArtifactName }}'),
                  eq(dependencies.TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.outputs['TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.TerraformChangesCheck.ChangesNeedApplying'], 'true'),
                  eq(dependencies.TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.outputs['TerraformDeployPlan_${{ parameters.TerraformArtifactName }}.TerraformChangesCheck.ChangesNeedManualVerification'], 'false')
                )
              )
            DependsOn:
              - ManualVerification_${{ parameters.TerraformArtifactName }}
              - TerraformDeployPlan_${{ parameters.TerraformArtifactName }}
          Pool: ${{ parameters.Pool }}
          TerraformArtifactName: ${{ parameters.TerraformArtifactName }}
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformDeploymentConfig: ${{ parameters.TerraformDeploymentConfig }}z
          EnvironmentName: ${{ parameters.EnvironmentName }}

  - ${{ if eq(parameters.IsDestroy, true) }}:
      - template: /jobs/terraform_deploy.yml
        parameters:
          CheckoutAlias: ${{ parameters.CheckoutAlias }}
          TerraformDeployMode: Destroy
          DependsOn: ${{ parameters.DependsOn }}
          Condition: ${{ parameters.Condition }}
          Pool: ${{ parameters.Pool }}
          TerraformArtifactName: ${{ parameters.TerraformArtifactName }}
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformDeploymentConfig: ${{ parameters.TerraformDeploymentConfig }}
          EnvironmentName: ${{ parameters.EnvironmentName }}