parameters:
  - name: TerraformVersion
    type: string
    default: '1.14.0'
    displayName: 'Version of Terraform CLI tool to use with the terraform files'

  - name: TerraformArtifactName
    type: string
    default: 'TerraformArtifact'
    displayName: 'Name for the artifact containing the terraform files for deployment'

  - name: EnvironmentConfig
    type: object
    # NO default - Consumer must provide this
    displayName: 'Environment configuration object (see docs/definition_docs/terraform_pipeline/environment_config.md)'

  - name: IsDestroy
    type: boolean
    default: false
    displayName: 'Indicates if the terraform destroy command should be executed'

stages:
  - stage: Deploy_${{ parameters.EnvironmentConfig.Name }}_Terraform
    displayName: 'Deploy ${{ parameters.EnvironmentConfig.Name }} Terraform'

    ${{ if or(not(parameters.EnvironmentConfig.Stage.DependsOn), eq(parameters.EnvironmentConfig.Stage.DependsOn, '')) }}:
      "environment '${{ parameters.EnvironmentConfig.Name }}' DependsOn is not properly defined and is a required field.": "Error"
    dependsOn: ${{ parameters.EnvironmentConfig.Stage.DependsOn }}
    ${{ if or(not(parameters.EnvironmentConfig.Stage.Condition), eq(parameters.EnvironmentConfig.Stage.Condition, '')) }}:
      "environment '${{ parameters.EnvironmentConfig.Name }}' Condition is not properly defined and is a required field.": "Error"
    condition: ${{ parameters.EnvironmentConfig.Stage.Condition }}

    jobs:
      - template: /jobs/terraform_gated_deployment.yml
        parameters:
          TerraformVersion: ${{ parameters.TerraformVersion }}
          TerraformArtifactName: ${{ parameters.TerraformArtifactName }}
          EnvironmentName: ${{ parameters.EnvironmentConfig.Name }}
          TerraformDeploymentConfig: ${{ parameters.EnvironmentConfig.TerraformDeploymentConfig }}
          IsDestroy: ${{ parameters.IsDestroy }}
